# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal

class MyComboBox(QtWidgets.QComboBox):
    mysignal = pyqtSignal()
    def mousePressEvent(self, event):
        print("emit")
        self.mysignal.emit()
        QtWidgets.QComboBox.mousePressEvent(self, event)
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_receive = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_receive.setGeometry(QtCore.QRect(240, 141, 511, 141))
        self.textBrowser_receive.setObjectName("textBrowser_receive")
        self.textEdit_transmit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_transmit.setGeometry(QtCore.QRect(240, 350, 511, 131))
        self.textEdit_transmit.setObjectName("textEdit_transmit")
        self.lcdNumber_rx = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rx.setGeometry(QtCore.QRect(240, 120, 71, 23))
        self.lcdNumber_rx.setObjectName("lcdNumber_rx")
        self.lcdNumber_tx = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_tx.setGeometry(QtCore.QRect(240, 330, 71, 23))
        self.lcdNumber_tx.setObjectName("lcdNumber_tx")
        self.textBrowser_status = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_status.setGeometry(QtCore.QRect(240, 40, 511, 31))
        self.textBrowser_status.setObjectName("textBrowser_status")
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setGeometry(QtCore.QRect(240, 500, 111, 28))
        self.pushButton_send.setObjectName("pushButton_send")
        self.pushButton_cmd1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd1.setGeometry(QtCore.QRect(370, 500, 111, 28))
        self.pushButton_cmd1.setObjectName("pushButton_cmd1")
        self.pushButton_cmd2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd2.setGeometry(QtCore.QRect(500, 500, 111, 28))
        self.pushButton_cmd2.setObjectName("pushButton_cmd2")
        self.pushButton_cmd3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd3.setGeometry(QtCore.QRect(630, 500, 111, 28))
        self.pushButton_cmd3.setObjectName("pushButton_cmd3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 20, 72, 15))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 100, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 310, 61, 16))
        self.label_8.setObjectName("label_8")
        self.radioButton_disable_receive = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_disable_receive.setGeometry(QtCore.QRect(330, 120, 151, 19))
        self.radioButton_disable_receive.setObjectName("radioButton_disable_receive")
        self.radioButton_enable_receive = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_enable_receive.setGeometry(QtCore.QRect(330, 100, 151, 19))
        self.radioButton_enable_receive.setObjectName("radioButton_enable_receive")
        self.radioButton_hex_display = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_hex_display.setGeometry(QtCore.QRect(490, 100, 131, 19))
        self.radioButton_hex_display.setObjectName("radioButton_hex_display")
        self.pushButton_reset_rx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset_rx.setGeometry(QtCore.QRect(640, 100, 111, 28))
        self.pushButton_reset_rx.setObjectName("pushButton_reset_rx")
        self.radioButton_ascii_display = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ascii_display.setGeometry(QtCore.QRect(490, 120, 131, 19))
        self.radioButton_ascii_display.setObjectName("radioButton_ascii_display")
        self.radioButton_ascii_send = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ascii_send.setGeometry(QtCore.QRect(490, 330, 131, 19))
        self.radioButton_ascii_send.setObjectName("radioButton_ascii_send")
        self.pushButton_reset_tx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset_tx.setGeometry(QtCore.QRect(640, 310, 111, 28))
        self.pushButton_reset_tx.setObjectName("pushButton_reset_tx")
        self.radioButton_manual_send = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_manual_send.setGeometry(QtCore.QRect(330, 330, 151, 19))
        self.radioButton_manual_send.setObjectName("radioButton_manual_send")
        self.radioButton_hex_send = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_hex_send.setGeometry(QtCore.QRect(490, 310, 131, 19))
        self.radioButton_hex_send.setObjectName("radioButton_hex_send")
        self.radioButton_auto_send = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_auto_send.setGeometry(QtCore.QRect(330, 310, 151, 19))
        self.radioButton_auto_send.setObjectName("radioButton_auto_send")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 80, 561, 20))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(210, 290, 561, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(200, 10, 20, 531))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.checkBox_rtscts = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rtscts.setGeometry(QtCore.QRect(40, 420, 151, 19))
        self.checkBox_rtscts.setObjectName("checkBox_rtscts")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 320, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 72, 15))
        self.label.setObjectName("label")
        self.comboBox_stopbits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stopbits.setGeometry(QtCore.QRect(40, 280, 151, 22))
        self.comboBox_stopbits.setObjectName("comboBox_stopbits")
        self.comboBox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_baudrate.setGeometry(QtCore.QRect(40, 100, 151, 22))
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.checkBox_dsrdtr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_dsrdtr.setGeometry(QtCore.QRect(40, 460, 141, 19))
        self.checkBox_dsrdtr.setObjectName("checkBox_dsrdtr")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 72, 15))
        self.label_2.setObjectName("label_2")
        self.checkBox_xonxoff = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_xonxoff.setGeometry(QtCore.QRect(40, 380, 151, 19))
        self.checkBox_xonxoff.setObjectName("checkBox_xonxoff")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 72, 15))
        self.label_5.setObjectName("label_5")
        self.pushButton_openport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openport.setGeometry(QtCore.QRect(60, 500, 111, 28))
        self.pushButton_openport.setObjectName("pushButton_openport")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 72, 15))
        self.label_4.setObjectName("label_4")
        self.comboBox_port = MyComboBox(self.centralwidget)
        self.comboBox_port.setGeometry(QtCore.QRect(40, 40, 151, 22))
        self.comboBox_port.setObjectName("comboBox_port")
        self.comboBox_bytesize = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_bytesize.setGeometry(QtCore.QRect(40, 160, 151, 22))
        self.comboBox_bytesize.setObjectName("comboBox_bytesize")
        self.comboBox_parity = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_parity.setGeometry(QtCore.QRect(40, 220, 151, 22))
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 72, 15))
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(760, 10, 20, 531))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(210, 530, 561, 20))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(210, 0, 561, 20))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 10, 20, 531))
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(20, 0, 191, 20))
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(20, 530, 191, 20))
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timeout.setGeometry(QtCore.QRect(40, 340, 151, 21))
        self.lineEdit_timeout.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.pushButton_cmd1.setText(_translate("MainWindow", "CMD1"))
        self.pushButton_cmd2.setText(_translate("MainWindow", "CMD2"))
        self.pushButton_cmd3.setText(_translate("MainWindow", "CMD3"))
        self.label_9.setText(_translate("MainWindow", "Status"))
        self.label_7.setText(_translate("MainWindow", "RX CNT"))
        self.label_8.setText(_translate("MainWindow", "TX CNT"))
        self.radioButton_disable_receive.setText(_translate("MainWindow", "disable receive"))
        self.radioButton_enable_receive.setText(_translate("MainWindow", "enable receive"))
        self.radioButton_hex_display.setText(_translate("MainWindow", "hex display"))
        self.pushButton_reset_rx.setText(_translate("MainWindow", "Reset"))
        self.radioButton_ascii_display.setText(_translate("MainWindow", "ascii dispaly"))
        self.radioButton_ascii_send.setText(_translate("MainWindow", "ascii send"))
        self.pushButton_reset_tx.setText(_translate("MainWindow", "Reset"))
        self.radioButton_manual_send.setText(_translate("MainWindow", "manual send"))
        self.radioButton_hex_send.setText(_translate("MainWindow", "hex send"))
        self.radioButton_auto_send.setText(_translate("MainWindow", "auto send"))
        self.checkBox_rtscts.setText(_translate("MainWindow", "rtscts enable "))
        self.label_6.setText(_translate("MainWindow", "Read Timeout"))
        self.label.setText(_translate("MainWindow", "Port"))
        self.checkBox_dsrdtr.setText(_translate("MainWindow", "dsrdtr enable "))
        self.label_2.setText(_translate("MainWindow", "BaudRate"))
        self.checkBox_xonxoff.setText(_translate("MainWindow", "xonxoff enable"))
        self.label_5.setText(_translate("MainWindow", "StopBits"))
        self.pushButton_openport.setText(_translate("MainWindow", "Open Port"))
        self.label_4.setText(_translate("MainWindow", "Parity"))
        self.label_3.setText(_translate("MainWindow", "ByteSize"))

